// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PotionCraft.Repository;

#nullable disable

namespace PotionCraft.Repository.Migrations
{
    [DbContext(typeof(PotionCraftDbContext))]
    [Migration("20260313170202_AddIsSelectedToPlayerCharacter")]
    partial class AddIsSelectedToPlayerCharacter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PotionCraft.Contracts.Models.Herb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalRule")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Habitats")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HerbType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Herbs");
                });

            modelBuilder.Entity("PotionCraft.Contracts.PlayerCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAlchemistSuppliesExpertise")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAlchemistSuppliesProficiency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHerbalismKitExpertise")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHerbalismKitProficiency")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPoisonerSuppliesExpertise")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPoisonerSuppliesProficiency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlayerCharacters");
                });
#pragma warning restore 612, 618
        }
    }
}
