// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PotionCraft.Repository;

#nullable disable

namespace PotionCraft.Repository.Migrations
{
    [DbContext(typeof(PotionCraftDbContext))]
    partial class PotionCraftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PotionCraft.Contracts.Models.Herb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Habitats")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HerbType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Herbs");
                });

            modelBuilder.Entity("PotionCraft.Contracts.PlayerCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SelectedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlayerCharacters");
                });

            modelBuilder.Entity("PotionCraft.Contracts.PlayerCharacter", b =>
                {
                    b.OwnsOne("PotionCraft.Contracts.Tool", "AlchemistTool", b1 =>
                        {
                            b1.Property<Guid>("PlayerCharacterId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Expertise")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Modifier")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerCharacterId");

                            b1.ToTable("PlayerCharacters");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterId");
                        });

                    b.OwnsOne("PotionCraft.Contracts.Tool", "HerbalismTool", b1 =>
                        {
                            b1.Property<Guid>("PlayerCharacterId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Expertise")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Modifier")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerCharacterId");

                            b1.ToTable("PlayerCharacters");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterId");
                        });

                    b.OwnsOne("PotionCraft.Contracts.Tool", "PoisonerTool", b1 =>
                        {
                            b1.Property<Guid>("PlayerCharacterId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Expertise")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Modifier")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("Proficiency")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerCharacterId");

                            b1.ToTable("PlayerCharacters");

                            b1.WithOwner()
                                .HasForeignKey("PlayerCharacterId");
                        });

                    b.Navigation("AlchemistTool")
                        .IsRequired();

                    b.Navigation("HerbalismTool")
                        .IsRequired();

                    b.Navigation("PoisonerTool")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
